# Generated by Django 4.0.3 on 2022-03-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=200)),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('start_container', models.CharField(max_length=50)),
                ('end_container', models.CharField(max_length=50)),
            ],
        ),
    ]
